version: "3.9"

services:
  db:
    build: ./backend/db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - 5432
    networks:
      - backend

  api:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5000
    volumes:
      - ./backend:/app
    expose:
      - 5000
    ports:
      - 5000:5000
    networks:
      - backend

networks:
  backend:
    driver: bridge
